"""fix in timezone without time zone for with timezone in field from notification

Revision ID: b13746a87b9d
Revises: bc8c582286cc
Create Date: 2025-09-02 00:03:32.762264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b13746a87b9d'
down_revision: Union[str, Sequence[str], None] = 'bc8c582286cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
