"""fix in timezone without time zone for with timezone in field from notification

Revision ID: bc8c582286cc
Revises: 52be06e2af7e
Create Date: 2025-09-01 23:59:49.399043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bc8c582286cc'
down_revision: Union[str, Sequence[str], None] = '52be06e2af7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
